## Время

In [22]:
import xlsxwriter
import pandas as pd
import numpy as np
from datetime import datetime as dt

import warnings
warnings.filterwarnings('ignore')

In [42]:
df1 = pd.read_excel('FTS_Февраль_2023_11488.xlsx')
df2 = pd.read_excel('Pernod_Ricard_Февраль_2023_11468.xlsx')
df3 = pd.read_excel('KazEuroTrade_Almaty_Февраль_2023_11469.xlsx')
df4 = pd.read_excel('KazEuroTrade_Region_Февраль_2023_11470.xlsx')
df5 = pd.read_excel('Jaqsy_Февраль_2023_11467.xlsx')
df6 = pd.read_excel('Рауик_Февраль_2023_11466.xlsx')
df7 = pd.read_excel('ИП_Сойка_Февраль_2023_11464.xlsx')
df8 = pd.read_excel('PMI_ToiMart_Февраль_2023_11472.xlsx')
df9 = pd.read_excel('PMI_Small_Февраль_2023_11475.xlsx')
df10 = pd.read_excel('PMI_Magnum_Февраль_2023_11476.xlsx')
df11 = pd.read_excel('PMI_Dina_Anvar_Февраль_2023_11473.xlsx')
df12 = pd.read_excel('KWS_Регион_Февраль_2023_11479.xlsx')
df13 = pd.read_excel('JFOOD_distribution_Февраль_2023_11465.xlsx')
df14 = pd.read_excel('Bonduelle_Февраль_2023_11480.xlsx')
df15 = pd.read_excel('A-Product_Февраль_2023_11481.xlsx')
df16 = pd.read_excel('Фото_Селфи_Февраль_2023_Merch_1_RK_11492.xlsx')

In [53]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16], axis=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30887 entries, 0 to 2925
Columns: 350 entries, ID анкеты to Фото Селфи
dtypes: float64(199), int64(2), object(149)
memory usage: 82.7+ MB

In [44]:
df['Дата начала работы'].value_counts()

04.02.2023 08:57    12
09.02.2023 08:43    12
06.02.2023 08:43    12
08.02.2023 08:40    12
01.02.2023 08:36    12
                    ..
01.02.2023 16:59     1
27.02.2023 15:31     1
01.02.2023 17:12     1
01.02.2023 17:13     1
08.02.2023 18:43     1
Name: Дата начала работы, Length: 13746, dtype: int64

In [48]:
df['Дата начала работы'].max()

'28.02.2023 11:41'

In [45]:
df['Дата начала работы'].dtype

dtype('O')

In [37]:
df.to_excel('время_февраль.xlsx')

In [11]:
df = pd.read_excel('2023_Фото_отчет_3D_10305_YLxeOlE.xlsx', sheet_name = 'data_2023-02-22 20 35')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 794 entries, 0 to 793
Data columns (total 18 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Точка: Customer Name                          794 non-null    object
 1   Точка: Customer Name Olap                     83 non-null     object
 2   Точка: Customer Name Prima                    73 non-null     object
 3   Точка: Адрес                                  794 non-null    object
 4   Точка: Код                                    794 non-null    object
 5   Исполнитель                                   794 non-null    object
 6   Дата сохранения анкеты                        794 non-null    datetime64[ns]
 7   Дата начала работы                            794 non-null    datetime64[ns]
 8   Дата окончания работы                         794 non-null    datetime64[ns]
 9   Фото Одометра                                 100 non-null    object
 10  Цифровые значения Одометра                    98 non-null     float64
 11  Статус ТТ : Открыта                           794 non-null    int64
 12  Статус ТТ : Закрыта                           794 non-null    int64
 13  Фото Hot Place/Фото Фасада ТТ                 767 non-null    object
 14  Фото Выкладки                                 794 non-null    object
 15  Была ли продажа устройства : Да               794 non-null    int64
 16  Была ли продажа устройства : Нет              794 non-null    int64
 17  Необходимо вести код продаваемого устройства  13 non-null     object
dtypes: datetime64[ns](3), float64(1), int64(4), object(10)
memory usage: 111.8+ KB

In [34]:
df

,ID анкеты,UUID,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,"Отметьте СКЮ, которого НЕТ в наличии в категории ПЕЧЕНЬЕ УПАКОВКЕ ФЛ/П : ПЕЧЕНЬЕ APRODUCT SOLOMKA СОЛЕНОЕ 350ГР ФЛ/П","Отметьте СКЮ, которого НЕТ в наличии в категории ПЕЧЕНЬЕ УПАКОВКЕ ФЛ/П : ПЕЧЕНЬЕ APRODUCT МАРИЯ С МОЛ КРЕМОМ 360ГР ФЛ/П","Отметьте СКЮ, которого НЕТ в наличии в категории ПЕЧЕНЬЕ УПАКОВКЕ ФЛ/П : ПЕЧЕНЬЕ APRODUCT МАРИЯ 350ГР ФЛ/П","Отметьте СКЮ, которого НЕТ в наличии в категории ПЕЧЕНЬЕ УПАКОВКЕ ФЛ/П : ПЕЧЕНЬЕ АPRODUCT БЕЛЫЙ СЕЗАМ 360ГР ФЛ/П","Отметьте СКЮ, которого НЕТ в наличии в категории ПЕЧЕНЬЕ УПАКОВКЕ ФЛ/П : ПЕЧЕНЬЕ АPRODUCT КРЕМИКИ С МОЛ КРЕМОМ 350ГР ФЛ/П","Отметьте СКЮ, которого НЕТ в наличии в категории ПЕЧЕНЬЕ УПАКОВКЕ ФЛ/П : ПЕЧЕНЬЕ APRODUCT ДОН ПОТАТО 360ГР ФЛ/П","Отметьте СКЮ, которого НЕТ в наличии в категории ПЕЧЕНЬЕ УПАКОВКЕ ФЛ/П : ПЕЧЕНЬЕ APRODUCT LEO С МОЛ КРЕМОМ 390ГР ФЛ/П","Отметьте СКЮ, которого НЕТ в наличии в категории ПЕЧЕНЬЕ УПАКОВКЕ ФЛ/П : ПЕЧЕНЬЕ A PRODUCT ЛЕГЕНДА АМЕРИКИ ПРЕМИУМ 180ГР ФЛ/П",Фото После работы ПЕЧЕНЬЕ УПАКОВКЕ ФЛ/П,Дата
0,2882965,3b2c75ae-193b-49a6-a13b-a5655f0ae4d0,Magnum Cash&Carry (АФ №04),Magnum Cash&Carry,Magnum,"Алматы, Медеуский район, ул. Халиуллина, 194",South-East,Almaty Dst.,Almaty,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-02
1,2883030,05050ba9-dc6e-452a-928f-70644273a22e,Small (ALA50),Скиф Трейд ТОО,Small,"Алматы, пр. Достык, 29",South-East,Almaty Dst.,Almaty,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-02
2,2883042,46b0d5d8-1aa3-4275-b0fb-918dff49a9c1,Small (ALA14),Скиф Трейд ТОО,Small,"Алматы, мкр. Орбита 4, 9",South-East,Almaty Dst.,Almaty,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-02
3,2883070,6a4bf5d4-9836-4d43-a143-45d978aec168,Magnum Express (АФ №53),Magnum Express,Magnum,"Алматы, пр. Сейфуллина 171",South-East,Almaty Dst.,Almaty,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-02
4,2883071,cb585b4f-9748-4587-a60c-2b282008c2f0,Magnum Express (АФ №53),Magnum Express,Magnum,"Алматы, пр. Сейфуллина 171",South-East,Almaty Dst.,Almaty,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3349,3096683,c1cec878-db47-44c8-93ea-91233fc1bcc7,Small (PVL11),Скиф Трейд ТОО,Small,"Павлодар, ул. Ак. Маргулана, 113",East,Pavlodar Dst.,Pavlodar,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-02-28
3350,3096684,e62b9bc6-566a-4953-b168-7e3ba6bd88f7,Small (PVL11),Скиф Трейд ТОО,Small,"Павлодар, ул. Ак. Маргулана, 113",East,Pavlodar Dst.,Pavlodar,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://object.pscloud.io/tradeexpert-photos/u...,2023-02-28
3351,3096759,2c00f32c-e5b3-43a6-b0ef-0df91a228c5f,Small (PVL03),Скиф Трейд ТОО,Small,"Павлодар, ул. Академика Сатпаева, 316/1",East,Pavlodar Dst.,Pavlodar,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-02-28
3352,3096770,bcc76eb7-6535-4f96-8050-889df85e2d6f,Small (EKB04),Скиф Трейд ТОО,Small,"Экибастуз, ул. Момыш-улы,54",East,Pavlodar Dst.,Ekibastuz,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-02-28
3353,3096778,0d4f336b-bc1e-4f8b-a384-5f9808380710,Small (PVL03),Скиф Трейд ТОО,Small,"Павлодар, ул. Академика Сатпаева, 316/1",East,Pavlodar Dst.,Pavlodar,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://object.pscloud.io/tradeexpert-photos/u...,2023-02-28

In [68]:
def parse_date(date_string):
    return pd.to_datetime(date_string, format='%d.%m.%Y %H:%M')

df = pd.read_excel('выгрузка_февраль.xlsx', converters={'Дата окончания работы': parse_date, 'Дата начала работы': parse_date})

In [ ]:
df = pd.read_excel('выгрузка_февраль.xlsx', parse_dates=['Дата окончания работы'], errors='coerce')

In [66]:
df['Дата окончания работы'].dtype

dtype('<M8[ns]')

In [67]:
df['Дата окончания работы'].max()

Timestamp('2023-02-28 11:43:00')

In [61]:

Я всё равно получаю ложное значение
df['Дата окончания работы'].max() = Timestamp('2023-12-02 20:05:00')

Timestamp('2023-12-02 20:05:00')

In [55]:
df['Дата окончания работы'] = pd.to_datetime(df['Дата окончания работы'])

In [56]:
df['Дата окончания работы'].max()

Timestamp('2023-12-02 20:05:00')

In [54]:
До форматьирования я имею:
df['Дата окончания работы'].max() 
out: '28.02.2023 11:43', т.е. 28 февраля

После преобразования даты я получаю ложное значение: 
df['Дата окончания работы'].max()  
out: Timestamp('2023-12-02 20:05:00'), т.е. 2 декабря - это неверно
    
Почему? Как исправить?

'28.02.2023 11:43'

In [38]:
df['Дата окончания работы'] = pd.to_datetime(df['Дата окончания работы'])
df['Дата начала работы'] = pd.to_datetime(df['Дата начала работы'])
df['Дата'] = df['Дата начала работы'].dt.date
df['Дата'] = pd.to_datetime(df['Дата'])

grouped_data = df.groupby(['Исполнитель', 'Дата']).agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})
grouped_data['Дата'] = grouped_data.index.get_level_values(1).strftime('%d.%m.%Y')
grouped_data

                        Дата начала работы Дата окончания работы        Дата
Исполнитель Дата
akb001      2023-01-02 2023-01-02 09:47:00   2023-01-02 09:53:00  02.01.2023
            2023-02-02 2023-02-02 09:53:00   2023-02-02 19:01:00  02.02.2023
            2023-02-13 2023-02-13 09:04:00   2023-02-13 19:54:00  13.02.2023
            2023-02-14 2023-02-14 09:31:00   2023-02-14 19:01:00  14.02.2023
            2023-02-15 2023-02-15 08:57:00   2023-02-15 19:07:00  15.02.2023
...                                    ...                   ...         ...
usk001      2023-06-02 2023-06-02 08:57:00   2023-06-02 17:42:00  02.06.2023
            2023-07-02 2023-07-02 08:59:00   2023-07-02 17:32:00  02.07.2023
            2023-08-02 2023-08-02 08:57:00   2023-08-02 12:55:00  02.08.2023
            2023-09-02 2023-09-02 08:56:00   2023-09-02 17:59:00  02.09.2023
            2023-10-02 2023-10-02 09:05:00   2023-10-02 13:50:00  02.10.2023

[2380 rows x 3 columns]

In [39]:
grouped_data.to_excel('время_февраль.xlsx')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30887 entries, 0 to 2925
Columns: 351 entries, ID анкеты to Дата
dtypes: datetime64[ns](3), float64(199), int64(2), object(147)
memory usage: 82.9+ MB

In [27]:
df['Дата окончания работы'] = pd.to_datetime(df['Дата окончания работы'])

df['Дата начала работы'] = pd.to_datetime(df['Дата начала работы'])

In [46]:
df['Дата сохранения анкеты'] = pd.to_datetime(df['Дата сохранения анкеты'])
df['Дата начала работы'] = pd.to_datetime(df['Дата начала работы'])
df['Дата окончания работы'] = pd.to_datetime(df['Дата окончания работы'])

In [30]:
df['Дата']

0      2023-01-02
1      2023-01-02
2      2023-01-02
3      2023-01-02
4      2023-01-02
          ...
3349   2023-02-28
3350   2023-02-28
3351   2023-02-28
3352   2023-02-28
3353   2023-02-28
Name: Дата, Length: 27961, dtype: datetime64[ns]

In [29]:

df['Дата окончания работы'] = pd.to_datetime(df['Дата окончания работы'])
df['Дата начала работы'] = pd.to_datetime(df['Дата начала работы'])
df['Дата'] = df['Дата начала работы'].dt.date
df['Дата'] = pd.to_datetime(df['Дата'])
df['Дата']                                                      
#df = df.drop_duplicates(subset=['ID анкеты'])

#df['Тип анкеты'] = np.where(df['Выберите Анкету : 1 работы'] == 1, 'До', 'После')

In [290]:
# Group data by "Project", "Point: Code", "Date" and "Исполнитель" columns
grouped_data = df.groupby(['Исполнитель', 'Дата'])
# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'Дата окончания работы': ['min', 'max']})

# Rename the columns to "Working Time" and "End Time"
#result.columns = ['Дата окончания работы', 'Дата окончания работы Min', 'Дата окончания работы Max']

result

                       Дата окончания работы
                                         min                 max
Исполнитель Дата
akb001      2023-02-01   2023-02-01 09:53:00 2023-02-01 09:53:00
            2023-02-02   2023-02-02 09:54:00 2023-02-02 19:01:00
            2023-02-03   2023-02-03 10:12:00 2023-02-03 19:25:00
            2023-02-04   2023-02-04 09:42:00 2023-02-04 19:58:00
            2023-02-06   2023-02-06 09:05:00 2023-02-06 19:07:00
...                                      ...                 ...
usk001      2023-02-13   2023-02-13 08:52:00 2023-02-13 14:53:00
            2023-02-14   2023-02-14 09:14:00 2023-02-14 16:13:00
            2023-02-15   2023-02-15 09:04:00 2023-02-15 17:55:00
            2023-02-16   2023-02-16 09:01:00 2023-02-16 15:26:00
            2023-02-17   2023-02-17 09:03:00 2023-02-17 13:20:00

[1533 rows x 2 columns]

In [292]:
result.to_excel('Время работы.xlsx')

In [294]:
df['Исполнитель'] = df['Исполнитель'].apply(lambda x: x.replace('@contineo.kz', ''))

In [ ]:
# Group the data by performer and date and aggregate the start and end times
grouped_data = df.groupby(['Исполнитель', 'Дата']).agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})

# Calculate the working time for each performer and date
grouped_data['Время работы'] = grouped_data['Дата окончания работы'] - grouped_data['Дата начала работы']

# Reset the index to make the performer and date columns regular columns
grouped_data = grouped_data.reset_index()

grouped_data

# В работе

In [ ]:
def parse_date(date_string):
    return pd.to_datetime(date_string, format='%d.%m.%Y %H:%M')

df = pd.read_excel('выгрузка_февраль.xlsx', converters={'Дата окончания работы': parse_date, 'Дата начала работы': parse_date})

In [31]:
# Group the data by performer and date and aggregate the start and end times

df['Дата окончания работы'] = pd.to_datetime(df['Дата окончания работы'])
df['Дата начала работы'] = pd.to_datetime(df['Дата начала работы'])
df['Дата'] = df['Дата начала работы'].dt.date
df['Дата'] = pd.to_datetime(df['Дата'])

grouped_data = df.groupby(['Исполнитель', 'Дата']).agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})

In [ ]:
def parse_date(date_string):
    return pd.to_datetime(date_string, format='%d.%m.%Y %H:%M')

df = pd.read_excel('выгрузка_февраль.xlsx', converters={'Дата окончания работы': parse_date,
                                                        'Дата начала работы': parse_date})
df['Дата'] = df['Дата начала работы'].dt.date
grouped_data = df.groupby(['Исполнитель', 'Дата']).agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})
Я получаю таблицу в результате этого кода.
Сделай столбец, который вычисляет разницу 
Создай сводную таблицу, где слева исполнители, а столбцы - это даты

In [32]:
grouped_data.to_excel('время на каждый день.xlsx')

In [21]:
grouped_data.to_excel('Время_.xlsx')

In [33]:
grouped_data

                        Дата начала работы Дата окончания работы
Исполнитель Дата
akb001      2023-01-02 2023-01-02 09:47:00   2023-01-02 09:53:00
            2023-02-02 2023-02-02 09:55:00   2023-02-02 19:01:00
            2023-02-13 2023-02-13 09:05:00   2023-02-13 19:54:00
            2023-02-14 2023-02-14 09:31:00   2023-02-14 19:01:00
            2023-02-15 2023-02-15 08:58:00   2023-02-15 19:07:00
...                                    ...                   ...
usk001      2023-06-02 2023-06-02 09:22:00   2023-06-02 17:42:00
            2023-07-02 2023-07-02 09:36:00   2023-07-02 17:32:00
            2023-08-02 2023-08-02 09:29:00   2023-08-02 12:55:00
            2023-09-02 2023-09-02 09:28:00   2023-09-02 17:59:00
            2023-10-02 2023-10-02 09:35:00   2023-10-02 13:50:00

[2260 rows x 2 columns]

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20024 entries, 0 to 20023
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Проекты                         20024 non-null  object
 1   ID анкеты                       20024 non-null  int64
 2   Точка: Customer Name            20024 non-null  object
 3   Точка: Customer Name Olap       18659 non-null  object
 4   Точка: Customer Name Prima      18461 non-null  object
 5   Точка: Адрес                    20024 non-null  object
 6   Точка: Регион                   20024 non-null  object
 7   Точка: Область                  20024 non-null  object
 8   Точка: Город                    19697 non-null  object
 9   Точка: Район                    196 non-null    object
 10  Точка: Код                      20024 non-null  object
 11  Точка: Координаты               19906 non-null  object
 12  Исполнитель                     20024 non-null  object
 13  Координаты отправки анкеты      20024 non-null  object
 14  Дата сохранения анкеты          20024 non-null  datetime64[ns]
 15  Дата начала работы              20024 non-null  datetime64[ns]
 16  Дата окончания работы           20024 non-null  datetime64[ns]
 17  Общее время работы (минут)      20024 non-null  int64
 18  Выберите Анкету : 1 работы      20024 non-null  int64
 19  Выберите Анкету : После работы  20024 non-null  int64
 20  lfn                             18106 non-null  object
 21  Дата                            20024 non-null  datetime64[ns]
 22  Тип анкеты                      20024 non-null  object
dtypes: datetime64[ns](4), int64(4), object(15)
memory usage: 3.7+ MB

In [12]:
# group the data by 'Point: Code' and 'Work start date'
grouped = df.groupby(['Проекты', 'Исполнитель'])

In [133]:
# Group the data by performer and date and aggregate the start and end times
grouped_data = df.groupby(['Исполнитель', 'Проекты']).agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})

# Calculate the working time for each performer and date
grouped_data['Время работы'] = grouped_data['Дата окончания работы'] - grouped_data['Дата начала работы']

# Reset the index to make the performer and date columns regular columns
grouped_data = grouped_data.reset_index()

grouped_data

,Исполнитель,Проекты,Дата начала работы,Дата окончания работы,Время работы
0,akb001,PMI,2023-02-01 09:47:00,2023-02-17 14:27:00,16 days 04:40:00
1,akb001,Фото-селфи,2023-02-02 09:53:00,2023-02-17 09:56:00,15 days 00:03:00
2,akb002,PMI,2023-02-01 09:49:00,2023-02-17 15:31:00,16 days 05:42:00
3,akb003@contineo.kz,PMI,2023-02-01 11:18:00,2023-02-17 15:23:00,16 days 04:05:00
4,akb003@contineo.kz,Фото-селфи,2023-02-01 11:13:00,2023-02-17 11:53:00,16 days 00:40:00
...,...,...,...,...,...
773,trz002,Фото-селфи,2023-01-02 07:49:00,2023-02-17 08:26:00,46 days 00:37:00
774,usk001,A-Product,2023-02-01 12:03:00,2023-02-16 12:49:00,15 days 00:46:00
775,usk001,KazEuro,2023-02-01 10:14:00,2023-02-17 13:20:00,16 days 03:06:00
776,usk001,PMI,2023-02-01 12:30:00,2023-02-17 11:33:00,15 days 23:03:00
777,usk001,Фото-селфи,2023-02-01 09:01:00,2023-02-17 09:03:00,16 days 00:02:00

In [151]:
import pandas as pd

# filter the data for the "Photo-selfie" project
#photo_selfie_data = df[df['Проекты'] == 'Фото-селфи']

# calculate the start and end times for each contractor
contractor_data = df.groupby('Исполнитель').agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})

# calculate the total work time for each contractor
contractor_data['Общее время работы'] = (contractor_data['Дата окончания работы'] - contractor_data['Дата начала работы']).dt.total_seconds() / 3600

# print the result
contractor_data

,Дата начала работы,Дата окончания работы,Общее время работы
Исполнитель,,,
akb001,2023-02-01 09:47:00,2023-02-17 14:27:00,388.666667
akb002,2023-02-01 09:49:00,2023-02-17 15:31:00,389.700000
akb003@contineo.kz,2023-02-01 11:13:00,2023-02-17 15:23:00,388.166667
akb004,2023-02-01 08:18:00,2023-02-17 14:12:00,389.900000
alm001,2023-02-01 08:57:00,2023-02-17 13:31:00,388.566667
...,...,...,...
trk001,2023-02-01 09:57:00,2023-02-17 11:07:00,385.166667
trk002@contineo.kz,2023-02-01 09:33:00,2023-02-17 14:44:00,389.183333
trz001,2023-02-01 09:35:00,2023-02-17 11:54:00,386.316667
trz002,2023-01-02 07:49:00,2023-02-17 14:56:00,1111.116667
usk001,2023-02-01 09:01:00,2023-02-17 13:20:00,388.316667

In [ ]:
There is a table: df[['Project', 'Point: Customer Name', 'Point: Code', 'Contractor', 'Date when questionnaire was saved', 'Start date', 'End date'.

In the column "Project" there is a value "Photo-selfie". For this value, you need to take the “'Start Date' for each contractor as the start of work. And the end time must be taken according to the maximum value in the 'End date'.
As a result, you need to get a table indicating the artist and the total time of work (Date of completion of work'.max - 'Date of start of work' (“Photo-selfie”).

But Date of completion of work' and  'Date of start of work' have object type

In [139]:
contractor_data

,Дата начала работы,Дата окончания работы,Общее время работы
Исполнитель,,,
akb001,2023-02-01 09:47:00,2023-02-17 14:27:00,388.666667
akb002,2023-02-01 09:49:00,2023-02-17 15:31:00,389.700000
akb003@contineo.kz,2023-02-01 11:13:00,2023-02-17 15:23:00,388.166667
akb004,2023-02-01 08:18:00,2023-02-17 14:12:00,389.900000
alm001,2023-02-01 08:57:00,2023-02-17 13:31:00,388.566667
...,...,...,...
trk001,2023-02-01 09:57:00,2023-02-17 11:07:00,385.166667
trk002@contineo.kz,2023-02-01 09:33:00,2023-02-17 14:44:00,389.183333
trz001,2023-02-01 09:35:00,2023-02-17 11:54:00,386.316667
trz002,2023-01-02 07:49:00,2023-02-17 14:56:00,1111.116667
usk001,2023-02-01 09:01:00,2023-02-17 13:20:00,388.316667

In [135]:
contractor_data

,Дата начала работы,Дата окончания работы,Общее время работы
Исполнитель,,,
akb001,2023-02-01 09:47:00,2023-02-17 14:27:00,388.666667
akb002,2023-02-01 09:49:00,2023-02-17 15:31:00,389.700000
akb003@contineo.kz,2023-02-01 11:13:00,2023-02-17 15:23:00,388.166667
akb004,2023-02-01 08:18:00,2023-02-17 14:12:00,389.900000
alm001,2023-02-01 08:57:00,2023-02-17 13:31:00,388.566667
...,...,...,...
trk001,2023-02-01 09:57:00,2023-02-17 11:07:00,385.166667
trk002@contineo.kz,2023-02-01 09:33:00,2023-02-17 14:44:00,389.183333
trz001,2023-02-01 09:35:00,2023-02-17 11:54:00,386.316667
trz002,2023-01-02 07:49:00,2023-02-17 14:56:00,1111.116667
usk001,2023-02-01 09:01:00,2023-02-17 13:20:00,388.316667

In [142]:
if 'Выберите анкету : До работы' in df.columns:
    before_col = 'Выберите анкету : До работы'
elif 'Анкета : До работы' in df.columns:
    before_col = 'Анкета : До работы'
elif 'Выберите Анкету : До Работы' in df.columns:
    before_col = 'Выберите Анкету : До Работы'
elif 'Выберите Анкету : До работы' in df.columns:
    before_col = 'Выберите Анкету : До работы'        
else:
    print('\n'+"Столбец с именем 'Анкета : До работы' или 'Выберите анкету : До работы' не найден!"+'\n')
    before_col = input('Введите имя столбца с информацией о том, что анкета до работы: ')

In [145]:
df['Дата'] = df['Дата начала работы'].dt.date
                                                      
df = df.drop_duplicates(subset=['ID анкеты'])

df['Тип анкеты'] = np.where(df[before_col] == 1, 'До', 'После')

# group the data by 'Point: Code' and 'Work start date'
grouped = df.groupby(['Проекты', 'Точка: Код', 'Дата'])

In [147]:
# Calculate the maximum "Дата окончания работы" and minimum "Дата начала работы" for each group
grouped_data = grouped.agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})

# Calculate the difference between the maximum and minimum values
grouped_data['Время работы в часах'] = (grouped_data['Дата окончания работы'] - grouped_data['Дата начала работы']).dt.total_seconds() / 3600

# Assign the result to the last row for each group
result = df.copy()

df['Время работы в часах'] = None

for index, row in result.iterrows():
    start_time = row['Дата начала работы']
    end_time = row['Дата окончания работы']
    if pd.notna(start_time) and pd.notna(end_time):
        working_time = end_time - start_time
        result.at[index, 'Время работы в часах'] = working_time

result

,Проекты,ID анкеты,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,Дата сохранения анкеты,Дата начала работы,Дата окончания работы,Общее время работы (минут),Выберите Анкету : До работы,Выберите Анкету : После работы,lfn,Тип анкеты,Дата,Время работы в часах
0,A-Product,2885591,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 15:15:00,2023-02-01 15:10:00,2023-02-01 15:11:00,1,До,0,44958A-ProductMagnum (НСФ №76)До,После,2023-02-01,0 days 00:01:00
1,A-Product,2887451,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 18:25:00,2023-02-01 15:11:00,2023-02-01 18:25:00,194,После,1,44958A-ProductMagnum (НСФ №76)После,После,2023-02-01,0 days 03:14:00
2,A-Product,2884764,Magnum Atak (КЗФ №01),Magnum Atak,Magnum,"Кызылорда, Жибек Жолы, 13 (Aray City Mall)",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 13:42:00,2023-02-01 12:38:00,2023-02-01 12:40:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №01)До,После,2023-02-01,0 days 00:02:00
3,A-Product,2887442,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 18:24:00,2023-02-01 17:06:00,2023-02-01 17:07:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №02)До,После,2023-02-01,0 days 00:01:00
4,A-Product,2888219,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 19:47:00,2023-02-01 18:42:00,2023-02-01 18:45:00,3,После,1,44958A-ProductMagnum Atak (КЗФ №02)После,После,2023-02-01,0 days 00:03:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20019,Фото-селфи,3011246,Magnum Exspress (ТРФ №03),Magnum Exspress,Magnum,"Туркестан, ул. Абылай хана, 58А",South,Turkestan Dst.,Turkestan,NaN,...,2023-02-17 14:37:00,2023-02-17 12:08:00,2023-02-17 12:09:00,0,1,0,NaN,До,2023-02-17,0 days 00:01:00
20020,Фото-селфи,3011692,Magnum Express (АФ №50),Magnum Express,Magnum,"Алматы, ул. Толе би, 229",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:09:00,2023-02-17 15:09:00,2023-02-17 15:09:00,0,0,1,NaN,После,2023-02-17,0 days 00:00:00
20021,Фото-селфи,3011816,Magnum Atak (АФ №05),Magnum Atak,Magnum,"Алматы, ул. Толе би, 285",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:18:00,2023-02-17 15:17:00,2023-02-17 15:17:00,1,1,0,NaN,До,2023-02-17,0 days 00:00:00
20022,Фото-селфи,3012657,Small (ALA39),Скиф Трейд ТОО,Small,"Алматы, с. Алмалыбак, ул. Ерлепесова , 40",South-East,Almaty Dst.,Kaskelen,NaN,...,2023-02-17 16:15:00,2023-02-17 14:59:00,2023-02-17 14:59:00,0,0,1,NaN,После,2023-02-17,0 days 00:00:00
20023,Фото-селфи,3012681,Magnum Express (НСФ №10),Magnum Express,Magnum,"Нур-Султан, ул. Биржан Сала, 7а",Central,Astana Dst.,Nur-Sultan,NaN,...,2023-02-17 16:17:00,2023-02-17 16:17:00,2023-02-17 16:17:00,0,1,0,NaN,До,2023-02-17,0 days 00:00:00

In [149]:
# Group the data by "Точка: Код" and "Дата начала работы"
grouped = df.groupby(['Точка: Код', 'Дата начала работы'])

# Calculate the maximum "Дата окончания работы" and minimum "Дата начала работы" for each group
grouped_data = grouped.agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})

# Calculate the difference between the maximum and minimum values
grouped_data['Working Time'] = (grouped_data['Дата окончания работы'] - grouped_data['Дата начала работы']).dt.total_seconds() / 60

# Assign the result to the last row for each group
result = df.copy()
result['Working Time'] = None
for name, group in grouped_data.iterrows():
    point_code = name[0]
    work_date = name[1]
    last_row = result.loc[(result['Точка: Код'] == point_code) & (result['Дата начала работы'] == work_date)].tail(1)
    result.loc[last_row.index, 'Working Time'] = group['Working Time']
    
    
result

,Проекты,ID анкеты,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,Дата начала работы,Дата окончания работы,Общее время работы (минут),Выберите Анкету : До работы,Выберите Анкету : После работы,lfn,Тип анкеты,Дата,Время работы в часах,Working Time
0,A-Product,2885591,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 15:10:00,2023-02-01 15:11:00,1,До,0,44958A-ProductMagnum (НСФ №76)До,После,2023-02-01,None,1.0
1,A-Product,2887451,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 15:11:00,2023-02-01 18:25:00,194,После,1,44958A-ProductMagnum (НСФ №76)После,После,2023-02-01,None,194.0
2,A-Product,2884764,Magnum Atak (КЗФ №01),Magnum Atak,Magnum,"Кызылорда, Жибек Жолы, 13 (Aray City Mall)",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 12:38:00,2023-02-01 12:40:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №01)До,После,2023-02-01,None,2.0
3,A-Product,2887442,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 17:06:00,2023-02-01 17:07:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №02)До,После,2023-02-01,None,1.0
4,A-Product,2888219,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 18:42:00,2023-02-01 18:45:00,3,После,1,44958A-ProductMagnum Atak (КЗФ №02)После,После,2023-02-01,None,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20019,Фото-селфи,3011246,Magnum Exspress (ТРФ №03),Magnum Exspress,Magnum,"Туркестан, ул. Абылай хана, 58А",South,Turkestan Dst.,Turkestan,NaN,...,2023-02-17 12:08:00,2023-02-17 12:09:00,0,1,0,NaN,До,2023-02-17,None,1.0
20020,Фото-селфи,3011692,Magnum Express (АФ №50),Magnum Express,Magnum,"Алматы, ул. Толе би, 229",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:09:00,2023-02-17 15:09:00,0,0,1,NaN,После,2023-02-17,None,0.0
20021,Фото-селфи,3011816,Magnum Atak (АФ №05),Magnum Atak,Magnum,"Алматы, ул. Толе би, 285",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:17:00,2023-02-17 15:17:00,1,1,0,NaN,До,2023-02-17,None,0.0
20022,Фото-селфи,3012657,Small (ALA39),Скиф Трейд ТОО,Small,"Алматы, с. Алмалыбак, ул. Ерлепесова , 40",South-East,Almaty Dst.,Kaskelen,NaN,...,2023-02-17 14:59:00,2023-02-17 14:59:00,0,0,1,NaN,После,2023-02-17,None,0.0
20023,Фото-селфи,3012681,Magnum Express (НСФ №10),Magnum Express,Magnum,"Нур-Султан, ул. Биржан Сала, 7а",Central,Astana Dst.,Nur-Sultan,NaN,...,2023-02-17 16:17:00,2023-02-17 16:17:00,0,1,0,NaN,До,2023-02-17,None,0.0

In [ ]:
df.update(result)

In [148]:
result

,Проекты,ID анкеты,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,Дата сохранения анкеты,Дата начала работы,Дата окончания работы,Общее время работы (минут),Выберите Анкету : До работы,Выберите Анкету : После работы,lfn,Тип анкеты,Дата,Время работы в часах
0,A-Product,2885591,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 15:15:00,2023-02-01 15:10:00,2023-02-01 15:11:00,1,До,0,44958A-ProductMagnum (НСФ №76)До,После,2023-02-01,0 days 00:01:00
1,A-Product,2887451,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 18:25:00,2023-02-01 15:11:00,2023-02-01 18:25:00,194,После,1,44958A-ProductMagnum (НСФ №76)После,После,2023-02-01,0 days 03:14:00
2,A-Product,2884764,Magnum Atak (КЗФ №01),Magnum Atak,Magnum,"Кызылорда, Жибек Жолы, 13 (Aray City Mall)",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 13:42:00,2023-02-01 12:38:00,2023-02-01 12:40:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №01)До,После,2023-02-01,0 days 00:02:00
3,A-Product,2887442,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 18:24:00,2023-02-01 17:06:00,2023-02-01 17:07:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №02)До,После,2023-02-01,0 days 00:01:00
4,A-Product,2888219,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 19:47:00,2023-02-01 18:42:00,2023-02-01 18:45:00,3,После,1,44958A-ProductMagnum Atak (КЗФ №02)После,После,2023-02-01,0 days 00:03:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20019,Фото-селфи,3011246,Magnum Exspress (ТРФ №03),Magnum Exspress,Magnum,"Туркестан, ул. Абылай хана, 58А",South,Turkestan Dst.,Turkestan,NaN,...,2023-02-17 14:37:00,2023-02-17 12:08:00,2023-02-17 12:09:00,0,1,0,NaN,До,2023-02-17,0 days 00:01:00
20020,Фото-селфи,3011692,Magnum Express (АФ №50),Magnum Express,Magnum,"Алматы, ул. Толе би, 229",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:09:00,2023-02-17 15:09:00,2023-02-17 15:09:00,0,0,1,NaN,После,2023-02-17,0 days 00:00:00
20021,Фото-селфи,3011816,Magnum Atak (АФ №05),Magnum Atak,Magnum,"Алматы, ул. Толе би, 285",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:18:00,2023-02-17 15:17:00,2023-02-17 15:17:00,1,1,0,NaN,До,2023-02-17,0 days 00:00:00
20022,Фото-селфи,3012657,Small (ALA39),Скиф Трейд ТОО,Small,"Алматы, с. Алмалыбак, ул. Ерлепесова , 40",South-East,Almaty Dst.,Kaskelen,NaN,...,2023-02-17 16:15:00,2023-02-17 14:59:00,2023-02-17 14:59:00,0,0,1,NaN,После,2023-02-17,0 days 00:00:00
20023,Фото-селфи,3012681,Magnum Express (НСФ №10),Magnum Express,Magnum,"Нур-Султан, ул. Биржан Сала, 7а",Central,Astana Dst.,Nur-Sultan,NaN,...,2023-02-17 16:17:00,2023-02-17 16:17:00,2023-02-17 16:17:00,0,1,0,NaN,До,2023-02-17,0 days 00:00:00

In [ ]:
# Group the data by "Точка: Код" and "Дата начала работы"
grouped = df.groupby(['Точка: Код', 'Дата начала работы'])

# Calculate the maximum "Дата окончания работы" and minimum "Дата начала работы" for each group
grouped_data = grouped.agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})

# Calculate the difference between the maximum and minimum values
grouped_data['Working Time'] = (grouped_data['Дата окончания работы'] - grouped_data['Дата начала работы']).dt.total_seconds() / 60

# Assign the result to the last row for each group
result = df.copy()
result['Working Time'] = None
for name, group in grouped_data.iterrows():
    point_code = name[0]
    work_date = name[1]
    last_row = result.loc[(result['Точка: Код'] == point_code) & (result['Дата начала работы'] == work_date)].tail(1)
    result.loc[last_row.index, 'Working Time'] = group['Working Time']

In [179]:
# Group the data by "Точка: Код" and "Дата начала работы"
grouped = df.groupby(['Точка: Код', 'Дата начала работы'])

# Calculate the maximum "Дата окончания работы" and minimum "Дата начала работы" for each group
grouped_data = grouped.agg({'Дата начала работы': 'min', 'Дата окончания работы': 'max'})

# Calculate the difference between the maximum and minimum values
grouped_data['Working Time'] = (grouped_data['Дата окончания работы'] - grouped_data['Дата начала работы']).dt.total_seconds() / 60

# Assign the result to the last row for each group
result = df.copy()
result['Working Time'] = None
for name, group in grouped_data.iterrows():
    point_code = name[0]
    work_date = name[1]
    last_row = result.loc[(result['Точка: Код'] == point_code) & (result['Дата начала работы'] == work_date)].tail(1)
    result.loc[last_row.index, 'Working Time'] = group['Working Time']

In [181]:
df

,Проекты,ID анкеты,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,Координаты отправки анкеты,Дата сохранения анкеты,Дата начала работы,Дата окончания работы,Общее время работы (минут),Выберите Анкету : До работы,Выберите Анкету : После работы,lfn,Дата,Тип анкеты
0,A-Product,2885591,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,"51.1131917,71.4215717",2023-02-01 15:15:00,2023-02-01 15:10:00,2023-02-01 15:11:00,1,До,0,44958A-ProductMagnum (НСФ №76)До,2023-02-01,После
1,A-Product,2887451,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,"51.1132751,71.4214995",2023-02-01 18:25:00,2023-02-01 15:11:00,2023-02-01 18:25:00,194,После,1,44958A-ProductMagnum (НСФ №76)После,2023-02-01,После
2,A-Product,2884764,Magnum Atak (КЗФ №01),Magnum Atak,Magnum,"Кызылорда, Жибек Жолы, 13 (Aray City Mall)",South,Kyzylorda Dst.,Kyzylorda,NaN,...,"44.8064132,65.5190081",2023-02-01 13:42:00,2023-02-01 12:38:00,2023-02-01 12:40:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №01)До,2023-02-01,После
3,A-Product,2887442,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,"44.8464553,65.5014177",2023-02-01 18:24:00,2023-02-01 17:06:00,2023-02-01 17:07:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №02)До,2023-02-01,После
4,A-Product,2888219,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,"44.8465539,65.5014241",2023-02-01 19:47:00,2023-02-01 18:42:00,2023-02-01 18:45:00,3,После,1,44958A-ProductMagnum Atak (КЗФ №02)После,2023-02-01,После
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20019,Фото-селфи,3011246,Magnum Exspress (ТРФ №03),Magnum Exspress,Magnum,"Туркестан, ул. Абылай хана, 58А",South,Turkestan Dst.,Turkestan,NaN,...,"42.418291,69.8285368",2023-02-17 14:37:00,2023-02-17 12:08:00,2023-02-17 12:09:00,0,1,0,NaN,2023-02-17,До
20020,Фото-селфи,3011692,Magnum Express (АФ №50),Magnum Express,Magnum,"Алматы, ул. Толе би, 229",South-East,Almaty Dst.,Almaty,NaN,...,"43.2510872,76.8805402",2023-02-17 15:09:00,2023-02-17 15:09:00,2023-02-17 15:09:00,0,0,1,NaN,2023-02-17,После
20021,Фото-селфи,3011816,Magnum Atak (АФ №05),Magnum Atak,Magnum,"Алматы, ул. Толе би, 285",South-East,Almaty Dst.,Almaty,NaN,...,"43.246172,76.8534654",2023-02-17 15:18:00,2023-02-17 15:17:00,2023-02-17 15:17:00,1,1,0,NaN,2023-02-17,До
20022,Фото-селфи,3012657,Small (ALA39),Скиф Трейд ТОО,Small,"Алматы, с. Алмалыбак, ул. Ерлепесова , 40",South-East,Almaty Dst.,Kaskelen,NaN,...,"43.214537933186804,76.68176302480596",2023-02-17 16:15:00,2023-02-17 14:59:00,2023-02-17 14:59:00,0,0,1,NaN,2023-02-17,После
20023,Фото-селфи,3012681,Magnum Express (НСФ №10),Magnum Express,Magnum,"Нур-Султан, ул. Биржан Сала, 7а",Central,Astana Dst.,Nur-Sultan,NaN,...,"51.1938772,71.4080982",2023-02-17 16:17:00,2023-02-17 16:17:00,2023-02-17 16:17:00,0,1,0,NaN,2023-02-17,До

In [180]:
result

,Проекты,ID анкеты,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,Дата сохранения анкеты,Дата начала работы,Дата окончания работы,Общее время работы (минут),Выберите Анкету : До работы,Выберите Анкету : После работы,lfn,Дата,Тип анкеты,Working Time
0,A-Product,2885591,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 15:15:00,2023-02-01 15:10:00,2023-02-01 15:11:00,1,До,0,44958A-ProductMagnum (НСФ №76)До,2023-02-01,После,1.0
1,A-Product,2887451,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 18:25:00,2023-02-01 15:11:00,2023-02-01 18:25:00,194,После,1,44958A-ProductMagnum (НСФ №76)После,2023-02-01,После,194.0
2,A-Product,2884764,Magnum Atak (КЗФ №01),Magnum Atak,Magnum,"Кызылорда, Жибек Жолы, 13 (Aray City Mall)",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 13:42:00,2023-02-01 12:38:00,2023-02-01 12:40:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №01)До,2023-02-01,После,2.0
3,A-Product,2887442,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 18:24:00,2023-02-01 17:06:00,2023-02-01 17:07:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №02)До,2023-02-01,После,1.0
4,A-Product,2888219,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 19:47:00,2023-02-01 18:42:00,2023-02-01 18:45:00,3,После,1,44958A-ProductMagnum Atak (КЗФ №02)После,2023-02-01,После,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20019,Фото-селфи,3011246,Magnum Exspress (ТРФ №03),Magnum Exspress,Magnum,"Туркестан, ул. Абылай хана, 58А",South,Turkestan Dst.,Turkestan,NaN,...,2023-02-17 14:37:00,2023-02-17 12:08:00,2023-02-17 12:09:00,0,1,0,NaN,2023-02-17,До,1.0
20020,Фото-селфи,3011692,Magnum Express (АФ №50),Magnum Express,Magnum,"Алматы, ул. Толе би, 229",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:09:00,2023-02-17 15:09:00,2023-02-17 15:09:00,0,0,1,NaN,2023-02-17,После,0.0
20021,Фото-селфи,3011816,Magnum Atak (АФ №05),Magnum Atak,Magnum,"Алматы, ул. Толе би, 285",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:18:00,2023-02-17 15:17:00,2023-02-17 15:17:00,1,1,0,NaN,2023-02-17,До,0.0
20022,Фото-селфи,3012657,Small (ALA39),Скиф Трейд ТОО,Small,"Алматы, с. Алмалыбак, ул. Ерлепесова , 40",South-East,Almaty Dst.,Kaskelen,NaN,...,2023-02-17 16:15:00,2023-02-17 14:59:00,2023-02-17 14:59:00,0,0,1,NaN,2023-02-17,После,0.0
20023,Фото-селфи,3012681,Magnum Express (НСФ №10),Magnum Express,Magnum,"Нур-Султан, ул. Биржан Сала, 7а",Central,Astana Dst.,Nur-Sultan,NaN,...,2023-02-17 16:17:00,2023-02-17 16:17:00,2023-02-17 16:17:00,0,1,0,NaN,2023-02-17,До,0.0

In [155]:
df

,Проекты,ID анкеты,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,Дата сохранения анкеты,Дата начала работы,Дата окончания работы,Общее время работы (минут),Выберите Анкету : До работы,Выберите Анкету : После работы,lfn,Тип анкеты,Дата,Время работы в часах
0,A-Product,2885591,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 15:15:00,2023-02-01 15:10:00,2023-02-01 15:11:00,1,До,0,44958A-ProductMagnum (НСФ №76)До,После,2023-02-01,None
1,A-Product,2887451,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 18:25:00,2023-02-01 15:11:00,2023-02-01 18:25:00,194,После,1,44958A-ProductMagnum (НСФ №76)После,После,2023-02-01,None
2,A-Product,2884764,Magnum Atak (КЗФ №01),Magnum Atak,Magnum,"Кызылорда, Жибек Жолы, 13 (Aray City Mall)",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 13:42:00,2023-02-01 12:38:00,2023-02-01 12:40:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №01)До,После,2023-02-01,None
3,A-Product,2887442,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 18:24:00,2023-02-01 17:06:00,2023-02-01 17:07:00,1,До,0,44958A-ProductMagnum Atak (КЗФ №02)До,После,2023-02-01,None
4,A-Product,2888219,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 19:47:00,2023-02-01 18:42:00,2023-02-01 18:45:00,3,После,1,44958A-ProductMagnum Atak (КЗФ №02)После,После,2023-02-01,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20019,Фото-селфи,3011246,Magnum Exspress (ТРФ №03),Magnum Exspress,Magnum,"Туркестан, ул. Абылай хана, 58А",South,Turkestan Dst.,Turkestan,NaN,...,2023-02-17 14:37:00,2023-02-17 12:08:00,2023-02-17 12:09:00,0,1,0,NaN,До,2023-02-17,None
20020,Фото-селфи,3011692,Magnum Express (АФ №50),Magnum Express,Magnum,"Алматы, ул. Толе би, 229",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:09:00,2023-02-17 15:09:00,2023-02-17 15:09:00,0,0,1,NaN,После,2023-02-17,None
20021,Фото-селфи,3011816,Magnum Atak (АФ №05),Magnum Atak,Magnum,"Алматы, ул. Толе би, 285",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 15:18:00,2023-02-17 15:17:00,2023-02-17 15:17:00,1,1,0,NaN,До,2023-02-17,None
20022,Фото-селфи,3012657,Small (ALA39),Скиф Трейд ТОО,Small,"Алматы, с. Алмалыбак, ул. Ерлепесова , 40",South-East,Almaty Dst.,Kaskelen,NaN,...,2023-02-17 16:15:00,2023-02-17 14:59:00,2023-02-17 14:59:00,0,0,1,NaN,После,2023-02-17,None
20023,Фото-селфи,3012681,Magnum Express (НСФ №10),Magnum Express,Magnum,"Нур-Султан, ул. Биржан Сала, 7а",Central,Astana Dst.,Nur-Sultan,NaN,...,2023-02-17 16:17:00,2023-02-17 16:17:00,2023-02-17 16:17:00,0,1,0,NaN,До,2023-02-17,None

In [153]:
df['Время работы в часах'].value_counts()

Series([], Name: Время работы в часах, dtype: int64)

In [ ]:

Есть таблица df[['Проект', 'Точка: Код', “Исполнитель”, “Дата начало работы”, “Даты окончания работы”, “Дата”]]

Создай новую таблицу расчёта времени, где будет группировка по “Исполнитель”,  “Точка: Код”, “Дата”. В новый столбец “Начало” сохрани дату и время из “Дата начало работы”, если столбец “Тип анкеты” равен “До”, и в новый столбец “Конец” сохрани дату и время из “Дата окончания работы”, если столбец “Тип анкеты” равен “После”.

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20024 entries, 0 to 20023
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Проекты                         20024 non-null  object
 1   ID анкеты                       20024 non-null  int64
 2   Точка: Customer Name            20024 non-null  object
 3   Точка: Customer Name Olap       18659 non-null  object
 4   Точка: Customer Name Prima      18461 non-null  object
 5   Точка: Адрес                    20024 non-null  object
 6   Точка: Регион                   20024 non-null  object
 7   Точка: Область                  20024 non-null  object
 8   Точка: Город                    19697 non-null  object
 9   Точка: Район                    196 non-null    object
 10  Точка: Код                      20024 non-null  object
 11  Точка: Координаты               19906 non-null  object
 12  Исполнитель                     20024 non-null  object
 13  Координаты отправки анкеты      20024 non-null  object
 14  Дата сохранения анкеты          20024 non-null  datetime64[ns]
 15  Дата начала работы              20024 non-null  datetime64[ns]
 16  Дата окончания работы           20024 non-null  datetime64[ns]
 17  Общее время работы (минут)      20024 non-null  int64
 18  Выберите Анкету : До работы     20024 non-null  object
 19  Выберите Анкету : После работы  20024 non-null  int64
 20  lfn                             18106 non-null  object
 21  Тип анкеты                      20024 non-null  object
 22  Дата                            20024 non-null  object
 23  Время работы в часах            0 non-null      object
dtypes: datetime64[ns](3), int64(3), object(18)
memory usage: 4.3+ MB

In [188]:


# Define a custom function to extract the start and end times for each group
def calculate_times(group):
    start = group.loc[group['Тип анкеты'] == 'До', 'Дата начала работы'].iloc[0]
    end = group.loc[group['Тип анкеты'] == 'После', 'Дата окончания работы'].iloc[0]
    return pd.DataFrame({'Start': start, 'End': end}, index=[0])

# Group the original dataframe by 'Contractor', 'Point: Code', and 'Date', and apply the custom function to each group
time_calculation = df.groupby(['Точка: Код', 'Дата']).apply(calculate_times)

# Print the resulting time calculation table
print(time_calculation)

IndexError: single positional indexer is out-of-bounds

In [189]:
df['Выберите Анкету : 1 работы'].value_counts()

1    10756
0     9268
Name: Выберите Анкету : 1 работы, dtype: int64

In [182]:
import pandas as pd

# assuming your original table is called df
new_table = df.groupby(['Проекты', 'Исполнитель', 'Точка: Код', 'Дата']).apply(lambda x: pd.Series({
    'Start': x.loc[x['Выберите Анкету : До работы'] == 'До', 'Дата начала работы'].iloc[0],
    'End': x.loc[x['Выберите Анкету : До работы'] == 'После', 'Дата окончания работы'].iloc[0]
})).reset_index()

# preview the new table
print(new_table.head())

IndexError: single positional indexer is out-of-bounds

In [190]:
df['Проекты'].value_counts()

PMI           5018
KazEuro       3411
Pernod        3109
A-Product     2027
Фото-селфи    1918
JFOOD         1180
KWS           1035
FTS            804
Bonduelle      628
РАУИК          453
Jaqsy          400
Сойка           41
Name: Проекты, dtype: int64

In [229]:
df = df.loc[df['Проекты'] != 'Фото-селфи']
df

,Проекты,ID анкеты,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,Дата сохранения анкеты,Дата начала работы,Дата окончания работы,Общее время работы (минут),Выберите Анкету : 1 работы,Выберите Анкету : После работы,lfn,Дата,Тип анкеты,Проверка
0,A-Product,2885591,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 15:15:00,2023-02-01 15:10:00,2023-02-01 15:11:00,1,1,0,44958A-ProductMagnum (НСФ №76)До,2023-02-01,До,
1,A-Product,2887451,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 18:25:00,2023-02-01 15:11:00,2023-02-01 18:25:00,194,0,1,44958A-ProductMagnum (НСФ №76)После,2023-02-01,После,
3,A-Product,2887442,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 18:24:00,2023-02-01 17:06:00,2023-02-01 17:07:00,1,1,0,44958A-ProductMagnum Atak (КЗФ №02)До,2023-02-01,До,
4,A-Product,2888219,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 19:47:00,2023-02-01 18:42:00,2023-02-01 18:45:00,3,0,1,44958A-ProductMagnum Atak (КЗФ №02)После,2023-02-01,После,
5,A-Product,2884119,Magnum Atak (КФ №02),Magnum Atak,Magnum,"Караганда, Бухар Жырау пр., 86",Central,Karaganda Dst.,Karaganda,NaN,...,2023-02-01 12:17:00,2023-02-01 12:11:00,2023-02-01 12:12:00,1,1,0,44958A-ProductMagnum Atak (КФ №02)До,2023-02-01,До,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18101,РАУИК,3008528,Magnum Express (АФ №70),Magnum,Magnum Express,"с. Отеген батыр, ул. Жансугурова 159",South-East,Almaty Dst.,Otegen Batyr,NaN,...,2023-02-17 11:13:00,2023-02-17 11:10:00,2023-02-17 11:12:00,3,0,1,44974РАУИКMagnum Express (АФ №70)После,2023-02-17,После,
18102,РАУИК,3008260,Magnum Express (АФ №72),Magnum Express,Magnum,"Алматы, ул. Шарипова, 145 к2",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 10:44:00,2023-02-17 09:07:00,2023-02-17 09:08:00,2,1,0,44974РАУИКMagnum Express (АФ №72)До,2023-02-17,До,
18103,РАУИК,3008332,Magnum Express (АФ №72),Magnum Express,Magnum,"Алматы, ул. Шарипова, 145 к2",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 10:52:00,2023-02-17 10:50:00,2023-02-17 10:52:00,1,0,1,44974РАУИКMagnum Express (АФ №72)После,2023-02-17,После,
18104,РАУИК,3007661,Magnum Express (КПФ №01),Magnum Express,Magnum,"Капшагай, ул. Кунаева, 4",South-East,Almaty Dst.,Капшагай,NaN,...,2023-02-17 09:31:00,2023-02-17 09:30:00,2023-02-17 09:31:00,1,1,0,44974РАУИКMagnum Express (КПФ №01)До,2023-02-17,До,
18105,РАУИК,3007719,Magnum Express (КПФ №01),Magnum Express,Magnum,"Капшагай, ул. Кунаева, 4",South-East,Almaty Dst.,Капшагай,NaN,...,2023-02-17 09:42:00,2023-02-17 09:40:00,2023-02-17 09:42:00,2,0,1,44974РАУИКMagnum Express (КПФ №01)После,2023-02-17,После,

In [230]:
df['Тип анкеты'].value_counts()

После    8638
До       8513
Name: Тип анкеты, dtype: int64

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18106 entries, 0 to 18105
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Проекты                         18106 non-null  object
 1   ID анкеты                       18106 non-null  int64
 2   Точка: Customer Name            18106 non-null  object
 3   Точка: Customer Name Olap       16899 non-null  object
 4   Точка: Customer Name Prima      16716 non-null  object
 5   Точка: Адрес                    18106 non-null  object
 6   Точка: Регион                   18106 non-null  object
 7   Точка: Область                  18106 non-null  object
 8   Точка: Город                    17792 non-null  object
 9   Точка: Район                    166 non-null    object
 10  Точка: Код                      18106 non-null  object
 11  Точка: Координаты               17996 non-null  object
 12  Исполнитель                     18106 non-null  object
 13  Координаты отправки анкеты      18106 non-null  object
 14  Дата сохранения анкеты          18106 non-null  datetime64[ns]
 15  Дата начала работы              18106 non-null  datetime64[ns]
 16  Дата окончания работы           18106 non-null  datetime64[ns]
 17  Общее время работы (минут)      18106 non-null  int64
 18  Выберите Анкету : 1 работы      18106 non-null  int64
 19  Выберите Анкету : После работы  18106 non-null  int64
 20  lfn                             18106 non-null  object
 21  Дата                            18106 non-null  datetime64[ns]
 22  Тип анкеты                      18106 non-null  object
dtypes: datetime64[ns](4), int64(4), object(15)
memory usage: 3.3+ MB

In [198]:
df = df.drop_duplicates(subset=['Проекты', 'Точка: Код', 'Дата', 'Тип анкеты'], keep='last')

In [237]:
# group the data by 'Point: Code' and 'Work start date'
grouped = df.groupby(['Проекты', 'Точка: Код', 'Дата'])

# count the number of 'Before' and 'After' questionnaires for each group
counts = grouped['Тип анкеты'].value_counts()

# create an empty 'Check' column
df['Проверка'] = ''

# create a DataFrame with the total counts for each day and point
total_counts = df.groupby(['Проекты', 'Точка: Код', 'Дата']).size().reset_index(name='Total')

for index, row in total_counts.iterrows():
    project = row['Проекты']
    point_code = row['Точка: Код']
    work_date = row['Дата']
    total_count = row['Total']
    before_count = counts[project, point_code, work_date, 'До'] if (project, point_code, work_date, 'До') in counts else 0
    after_count = counts[project, point_code, work_date, 'После'] if (project, point_code, work_date, 'После') in counts else 0
    if total_count == 2 and before_count == 1 and after_count == 1:
         df.loc[(df['Проекты'] == project) & (df['Точка: Код'] == point_code) & (df['Дата'] == work_date), 'Проверка'] = 'Правильно'
    elif total_count < 2:
        if before_count == 0:
            df.loc[(df['Проекты'] == project) & (df['Точка: Код'] == point_code) & (df['Дата'] == work_date), 'Проверка'] = 'Не хватает анкеты "До"'
        elif after_count == 0:
            df.loc[(df['Проекты'] == project) & (df['Точка: Код'] == point_code) & (df['Дата'] == work_date), 'Проверка'] = 'Не хватает анкеты "После"'
    else:
        if before_count > 1:
            df.loc[(df['Проекты'] == project) & (df['Точка: Код'] == point_code) & (df['Дата'] == work_date) & (df['Тип анкеты'] == 'До'), 'Проверка'] = 'Анкет "До" больше одной'
        elif after_count > 1:
            df.loc[(df['Проекты'] == project) & (df['Точка: Код'] == point_code) & (df['Дата'] == work_date) & (df['Тип анкеты'] == 'После'), 'Проверка'] = 'Анкет "После" больше одной'
            

df = df.sort_values(['Дата', 'Проекты', 'Точка: Customer Name', 'Тип анкеты'])

In [238]:
df['Проверка'].value_counts()

Correct                       17172
Не хватает анкеты "После"      1429
Анкет "До" больше одной         630
                                403
Анкет "После" больше одной      235
Не хватает анкеты "До"          155
Name: Проверка, dtype: int64

In [240]:
df_new = df.loc[df['Проверка'] == '']
df_new.to_excel('проверка.xlsx')

In [233]:
df['Проверка'].value_counts()

Correct                       16808
Не хватает анкеты "До"          171
Не хватает анкеты "После"       109
Анкет "После" больше одной       63
Name: Проверка, dtype: int64

In [241]:
df = df.loc[df['Проверка'] == "Correct"]

In [226]:
# create a boolean mask for rows where 'Check' is empty
mask = df['Проверка'] == ''

# keep only the rows where the mask is True
df = df[mask]

In [242]:
df

,Проекты,ID анкеты,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,Дата сохранения анкеты,Дата начала работы,Дата окончания работы,Общее время работы (минут),Выберите Анкету : 1 работы,Выберите Анкету : После работы,lfn,Дата,Тип анкеты,Проверка
0,A-Product,2885591,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 15:15:00,2023-02-01 15:10:00,2023-02-01 15:11:00,1,1,0,44958A-ProductMagnum (НСФ №76)До,2023-02-01,До,Correct
1,A-Product,2887451,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 18:25:00,2023-02-01 15:11:00,2023-02-01 18:25:00,194,0,1,44958A-ProductMagnum (НСФ №76)После,2023-02-01,После,Correct
3,A-Product,2887442,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 18:24:00,2023-02-01 17:06:00,2023-02-01 17:07:00,1,1,0,44958A-ProductMagnum Atak (КЗФ №02)До,2023-02-01,До,Correct
4,A-Product,2888219,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 19:47:00,2023-02-01 18:42:00,2023-02-01 18:45:00,3,0,1,44958A-ProductMagnum Atak (КЗФ №02)После,2023-02-01,После,Correct
5,A-Product,2884119,Magnum Atak (КФ №02),Magnum Atak,Magnum,"Караганда, Бухар Жырау пр., 86",Central,Karaganda Dst.,Karaganda,NaN,...,2023-02-01 12:17:00,2023-02-01 12:11:00,2023-02-01 12:12:00,1,1,0,44958A-ProductMagnum Atak (КФ №02)До,2023-02-01,До,Correct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20022,Фото-селфи,3012657,Small (ALA39),Скиф Трейд ТОО,Small,"Алматы, с. Алмалыбак, ул. Ерлепесова , 40",South-East,Almaty Dst.,Kaskelen,NaN,...,2023-02-17 16:15:00,2023-02-17 14:59:00,2023-02-17 14:59:00,0,0,1,NaN,2023-02-17,После,Correct
20002,Фото-селфи,3009258,Сабыржан Каскелен,NaN,NaN,"Каскелен, ул. Бердыкулова, 18",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 12:15:00,2023-02-17 12:14:00,2023-02-17 12:14:00,0,1,0,NaN,2023-02-17,До,Correct
20006,Фото-селфи,3009699,Сабыржан Каскелен,NaN,NaN,"Каскелен, ул. Бердыкулова, 18",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 12:47:00,2023-02-17 12:47:00,2023-02-17 12:47:00,0,0,1,NaN,2023-02-17,После,Correct
19995,Фото-селфи,3008573,Тоймарт Автодом,NaN,NaN,"Алматы, ул. Сатпаева, 90/21",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 11:18:00,2023-02-17 11:18:00,2023-02-17 11:18:00,0,1,0,NaN,2023-02-17,До,Correct
19999,Фото-селфи,3009006,Тоймарт Автодом,NaN,NaN,"Алматы, ул. Сатпаева, 90/21",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 11:55:00,2023-02-17 11:55:00,2023-02-17 11:55:00,0,0,1,NaN,2023-02-17,После,Correct

In [ ]:
У меня есть столбец "Время окончания работы". Я хочу получить разницу между максимальным и минимальным по каждому проекту, точка: код и дате, обозначив это в новой таблице для каждого исполнителя

In [218]:
df = df[df['Проверка'].isna()]

In [243]:
df['Тип анкеты'].value_counts()

До       8586
После    8586
Name: Тип анкеты, dtype: int64

In [220]:
df

Empty DataFrame
Columns: [Проекты, ID анкеты, Точка: Customer Name, Точка: Customer Name Olap, Точка: Customer Name Prima, Точка: Адрес, Точка: Регион, Точка: Область, Точка: Город, Точка: Район, Точка: Код, Точка: Координаты, Исполнитель, Координаты отправки анкеты, Дата сохранения анкеты, Дата начала работы, Дата окончания работы, Общее время работы (минут), Выберите Анкету : 1 работы, Выберите Анкету : После работы, lfn, Дата, Тип анкеты, Проверка]
Index: []

[0 rows x 24 columns]

In [246]:
import pandas as pd

# Group data by "Project", "Point: Code", "Date" and "Исполнитель" columns
grouped_data = df.groupby(['Исполнитель','Проекты', 'Точка: Customer Name', 'Дата'])

# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'Дата окончания работы': lambda x: x.max() - x.min()})

# Rename the "End Time" column to "Working Time"
result = result.rename(columns={'Дата окончания работы': 'Working Time'})

result

Как теперь подсчитать общее время работы для каждого исполнителя?

                                                         Working Time
Исполнитель Проекты Точка: Customer Name   Дата
akb001      PMI     Анвар Береке           2023-02-03 0 days 00:29:00
                                           2023-02-04 0 days 00:09:00
                                           2023-02-07 0 days 00:41:00
                                           2023-02-08 0 days 00:12:00
                                           2023-02-10 0 days 00:06:00
...                                                               ...
usk001      PMI     Magnum Hyper (УКФ №01) 2023-02-13 0 days 03:21:00
                                           2023-02-14 0 days 00:23:00
                                           2023-02-15 0 days 06:31:00
                                           2023-02-16 0 days 00:13:00
                                           2023-02-17 0 days 02:14:00

[8586 rows x 1 columns]

In [204]:
result['Working Time'].mean()

Timedelta('0 days 01:51:08.613138686')

In [206]:
result['Working Time'].mean()

Timedelta('0 days 01:51:44.179038333')

In [245]:
result['Working Time'].mean()

Timedelta('0 days 01:59:16.841369671')

In [247]:
result['Working Time'].mean()

Timedelta('0 days 01:59:16.841369671')

In [ ]:
grouped_data = df.groupby(['Projects', 'Point: Customer Name', 'Artist', 'Date']).agg({'Дата окончания работы': ['min', 'max']})

In [257]:
grouped_data = df.groupby(['Проекты', 'Точка: Customer Name', 'Исполнитель', 'Дата']).agg({'Дата окончания работы': ['min', 'max', 'max'-'min']})
grouped_data

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [253]:
# Group data by "Project", "Point: Code", "Date" and "Исполнитель" columns
grouped_data = df.groupby(['Проекты', 'Точка: Customer Name', 'Исполнитель', 'Дата'])
# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'Дата окончания работы': lambda x: x.max() - x.min(), 
                           'Дата окончания работы': ['min', 'max']})

# Rename the columns to "Working Time" and "End Time"
result.columns = ['Дата окончания работы', 'Дата окончания работы Min', 'Дата окончания работы Max']

result

                                                              Дата окончания работы  \
                                                                                min
Проекты    Точка: Customer Name Исполнитель        Дата
A-Product  Magnum (НСФ №76)     ast028@contineo.kz 2023-02-01   2023-02-01 15:11:00
                                                   2023-02-02   2023-02-02 16:05:00
                                                   2023-02-04   2023-02-04 09:52:00
                                                   2023-02-06   2023-02-06 16:15:00
                                                   2023-02-09   2023-02-09 15:29:00
...                                                                             ...
Фото-селфи Тоймарт Автодом      alm040             2023-02-10   2023-02-10 09:00:00
                                                   2023-02-11   2023-02-11 12:03:00
                                                   2023-02-15   2023-02-15 08:55:00
                                                   2023-02-17   2023-02-17 11:18:00
           Тоймарт Ужет         alm020             2023-02-03   2023-02-03 17:14:00


                                                                              max
Проекты    Точка: Customer Name Исполнитель        Дата
A-Product  Magnum (НСФ №76)     ast028@contineo.kz 2023-02-01 2023-02-01 18:25:00
                                                   2023-02-02 2023-02-02 16:07:00
                                                   2023-02-04 2023-02-04 09:53:00
                                                   2023-02-06 2023-02-06 16:32:00
                                                   2023-02-09 2023-02-09 18:10:00
...                                                                           ...
Фото-селфи Тоймарт Автодом      alm040             2023-02-10 2023-02-10 09:54:00
                                                   2023-02-11 2023-02-11 13:06:00
                                                   2023-02-15 2023-02-15 09:56:00
                                                   2023-02-17 2023-02-17 11:55:00
           Тоймарт Ужет         alm020             2023-02-03 2023-02-03 17:49:00

[8586 rows x 2 columns]

In [260]:
df

,Проекты,ID анкеты,Точка: Customer Name,Точка: Customer Name Olap,Точка: Customer Name Prima,Точка: Адрес,Точка: Регион,Точка: Область,Точка: Город,Точка: Район,...,Дата сохранения анкеты,Дата начала работы,Дата окончания работы,Общее время работы (минут),Выберите Анкету : 1 работы,Выберите Анкету : После работы,lfn,Дата,Тип анкеты,Проверка
0,A-Product,2885591,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 15:15:00,2023-02-01 15:10:00,2023-02-01 15:11:00,1,1,0,44958A-ProductMagnum (НСФ №76)До,2023-02-01,До,Correct
1,A-Product,2887451,Magnum (НСФ №76),Magnum Daily,Magnum,"г. Астана, ул. Акмешит, д. 9/2",Central,Astana Dst.,Astana,NaN,...,2023-02-01 18:25:00,2023-02-01 15:11:00,2023-02-01 18:25:00,194,0,1,44958A-ProductMagnum (НСФ №76)После,2023-02-01,После,Correct
3,A-Product,2887442,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 18:24:00,2023-02-01 17:06:00,2023-02-01 17:07:00,1,1,0,44958A-ProductMagnum Atak (КЗФ №02)До,2023-02-01,До,Correct
4,A-Product,2888219,Magnum Atak (КЗФ №02),Magnum Atak,Magnum,"Кызылорда, ул. Желтоксан, 7",South,Kyzylorda Dst.,Kyzylorda,NaN,...,2023-02-01 19:47:00,2023-02-01 18:42:00,2023-02-01 18:45:00,3,0,1,44958A-ProductMagnum Atak (КЗФ №02)После,2023-02-01,После,Correct
5,A-Product,2884119,Magnum Atak (КФ №02),Magnum Atak,Magnum,"Караганда, Бухар Жырау пр., 86",Central,Karaganda Dst.,Karaganda,NaN,...,2023-02-01 12:17:00,2023-02-01 12:11:00,2023-02-01 12:12:00,1,1,0,44958A-ProductMagnum Atak (КФ №02)До,2023-02-01,До,Correct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20022,Фото-селфи,3012657,Small (ALA39),Скиф Трейд ТОО,Small,"Алматы, с. Алмалыбак, ул. Ерлепесова , 40",South-East,Almaty Dst.,Kaskelen,NaN,...,2023-02-17 16:15:00,2023-02-17 14:59:00,2023-02-17 14:59:00,0,0,1,NaN,2023-02-17,После,Correct
20002,Фото-селфи,3009258,Сабыржан Каскелен,NaN,NaN,"Каскелен, ул. Бердыкулова, 18",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 12:15:00,2023-02-17 12:14:00,2023-02-17 12:14:00,0,1,0,NaN,2023-02-17,До,Correct
20006,Фото-селфи,3009699,Сабыржан Каскелен,NaN,NaN,"Каскелен, ул. Бердыкулова, 18",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 12:47:00,2023-02-17 12:47:00,2023-02-17 12:47:00,0,0,1,NaN,2023-02-17,После,Correct
19995,Фото-селфи,3008573,Тоймарт Автодом,NaN,NaN,"Алматы, ул. Сатпаева, 90/21",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 11:18:00,2023-02-17 11:18:00,2023-02-17 11:18:00,0,1,0,NaN,2023-02-17,До,Correct
19999,Фото-селфи,3009006,Тоймарт Автодом,NaN,NaN,"Алматы, ул. Сатпаева, 90/21",South-East,Almaty Dst.,Almaty,NaN,...,2023-02-17 11:55:00,2023-02-17 11:55:00,2023-02-17 11:55:00,0,0,1,NaN,2023-02-17,После,Correct

In [259]:
# Group data by "Project", "Point: Code", "Date" and "Исполнитель" columns
grouped_data = df.groupby(['Проекты', 'Точка: Customer Name', 'Исполнитель', 'Дата'])
# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'Дата окончания работы': lambda x: x.max() - x.min(), 
                           'Дата окончания работы': ['min', 'max']})

# Rename the columns to "Working Time" and "End Time"
#result.columns = ['Дата окончания работы', 'Дата окончания работы Min', 'Дата окончания работы Max']

result

                                                              Дата окончания работы  \
                                                                                min
Проекты    Точка: Customer Name Исполнитель        Дата
A-Product  Magnum (НСФ №76)     ast028@contineo.kz 2023-02-01   2023-02-01 15:11:00
                                                   2023-02-02   2023-02-02 16:05:00
                                                   2023-02-04   2023-02-04 09:52:00
                                                   2023-02-06   2023-02-06 16:15:00
                                                   2023-02-09   2023-02-09 15:29:00
...                                                                             ...
Фото-селфи Тоймарт Автодом      alm040             2023-02-10   2023-02-10 09:00:00
                                                   2023-02-11   2023-02-11 12:03:00
                                                   2023-02-15   2023-02-15 08:55:00
                                                   2023-02-17   2023-02-17 11:18:00
           Тоймарт Ужет         alm020             2023-02-03   2023-02-03 17:14:00


                                                                              max
Проекты    Точка: Customer Name Исполнитель        Дата
A-Product  Magnum (НСФ №76)     ast028@contineo.kz 2023-02-01 2023-02-01 18:25:00
                                                   2023-02-02 2023-02-02 16:07:00
                                                   2023-02-04 2023-02-04 09:53:00
                                                   2023-02-06 2023-02-06 16:32:00
                                                   2023-02-09 2023-02-09 18:10:00
...                                                                           ...
Фото-селфи Тоймарт Автодом      alm040             2023-02-10 2023-02-10 09:54:00
                                                   2023-02-11 2023-02-11 13:06:00
                                                   2023-02-15 2023-02-15 09:56:00
                                                   2023-02-17 2023-02-17 11:55:00
           Тоймарт Ужет         alm020             2023-02-03 2023-02-03 17:49:00

[8586 rows x 2 columns]

In [286]:
# Group data by "Project", "Point: Code", "Date" and "Исполнитель" columns
grouped_data = df.groupby(['Исполнитель', 'Дата'])
# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'Дата окончания работы': ['min', 'max']})

# Rename the columns to "Working Time" and "End Time"
#result.columns = ['Дата окончания работы', 'Дата окончания работы Min', 'Дата окончания работы Max']

result

                       Дата окончания работы
                                         min                 max
Исполнитель Дата
akb001      2023-02-02   2023-02-02 10:26:00 2023-02-02 19:01:00
            2023-02-03   2023-02-03 10:12:00 2023-02-03 19:25:00
            2023-02-04   2023-02-04 09:42:00 2023-02-04 19:58:00
            2023-02-06   2023-02-06 14:55:00 2023-02-06 19:07:00
            2023-02-07   2023-02-07 09:53:00 2023-02-07 15:31:00
...                                      ...                 ...
usk001      2023-02-13   2023-02-13 09:21:00 2023-02-13 14:53:00
            2023-02-14   2023-02-14 09:51:00 2023-02-14 16:13:00
            2023-02-15   2023-02-15 09:10:00 2023-02-15 17:55:00
            2023-02-16   2023-02-16 09:35:00 2023-02-16 15:26:00
            2023-02-17   2023-02-17 09:16:00 2023-02-17 13:20:00

[1395 rows x 2 columns]

In [262]:
((18*60+25)-(15*60+11))/60

3.2333333333333334

In [ ]:
# Group data by "Project", "Point: Code", "Date" and "Исполнитель" columns
grouped_data = df.groupby(['Исполнитель', 'Проекты', 'Точка: Customer Name', 'Дата'])
# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'Дата окончания работы': lambda x: x.max() - x.min()})

# Rename the columns to "Working Time" and "End Time"
#result.columns = ['Дата окончания работы', 'Дата окончания работы Min', 'Дата окончания работы Max']

result

In [266]:
result_sum = result.agg({'Дата окончания работы': lambda x: x.sum()})
result_sum

Дата окончания работы   711 days 05:04:00
dtype: timedelta64[ns]

In [282]:
# Group data by "Project", "Point: Code", "Date" and "Исполнитель" columns
grouped_data = df.groupby(['Исполнитель', 'Проекты', 'Точка: Customer Name', 'Дата'])
# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'Дата окончания работы': lambda x: x.max() - x.min()})

# Rename the columns to "Working Time" and "End Time"
#result.columns = ['Дата окончания работы', 'Дата окончания работы Min', 'Дата окончания работы Max']

result

                                                      Дата окончания работы
Исполнитель Проекты Точка: Customer Name   Дата
akb001      PMI     Анвар Береке           2023-02-03       0 days 00:29:00
                                           2023-02-04       0 days 00:09:00
                                           2023-02-07       0 days 00:41:00
                                           2023-02-08       0 days 00:12:00
                                           2023-02-10       0 days 00:06:00
...                                                                     ...
usk001      PMI     Magnum Hyper (УКФ №01) 2023-02-13       0 days 03:21:00
                                           2023-02-14       0 days 00:23:00
                                           2023-02-15       0 days 06:31:00
                                           2023-02-16       0 days 00:13:00
                                           2023-02-17       0 days 02:14:00

[8586 rows x 1 columns]

In [256]:
# Group data by "Project", "Point: Code", "Date" and "Исполнитель" columns
grouped_data = df.groupby(['Проекты', 'Точка: Customer Name', 'Исполнитель', 'Дата'])
# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'Дата окончания работы': lambda x: x.max() - x.min()})

# Rename the columns to "Working Time" and "End Time"
result = result.rename(columns={'Дата окончания работы': 'Working Time', 'min': 'Start Time', 'max': 'End Time'})

result

                                                                     Working Time
Проекты    Точка: Customer Name Исполнитель        Дата
A-Product  Magnum (НСФ №76)     ast028@contineo.kz 2023-02-01 2023-02-01 18:25:00
                                                   2023-02-02 2023-02-02 16:07:00
                                                   2023-02-04 2023-02-04 09:53:00
                                                   2023-02-06 2023-02-06 16:32:00
                                                   2023-02-09 2023-02-09 18:10:00
...                                                                           ...
Фото-селфи Тоймарт Автодом      alm040             2023-02-10 2023-02-10 09:54:00
                                                   2023-02-11 2023-02-11 13:06:00
                                                   2023-02-15 2023-02-15 09:56:00
                                                   2023-02-17 2023-02-17 11:55:00
           Тоймарт Ужет         alm020             2023-02-03 2023-02-03 17:49:00

[8586 rows x 1 columns]

In [ ]:
# Group data by "Project", "Point: Code", "Date" and "Artist" columns
grouped_data = df.groupby(['Projects', 'Point: Customer Name', 'Artist', 'Date'])

# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'End Time': lambda x: x.max() - x.min(), 'End Time': 'min', 'End Time': 'max'})

# Rename the columns to "Working Time" and "End Time"
result = result.rename(columns={'End Time': 'Working Time', 'min': 'Start Time', 'max': 'End Time'})

In [ ]:
# Group data by "Project", "Point: Code", "Date" and "Artist" columns
grouped_data = df.groupby(['Projects', 'Point: Customer Name', 'Artist', 'Date'])

# Calculate the difference between the maximum and minimum "End Time" values for each group,
# as well as the minimum and maximum "End Date" values
result = grouped_data.agg({'End Date': lambda x: x.max() - x.min(),
                           'End Date': ['min', 'max']})

# Rename the columns to "Working Time", "End Date Min", and "End Date Max"
result.columns = ['Working Time', 'End Date Min', 'End Date Max']

In [ ]:
# Group data by "Artist", "Project", "Point: Code", "Date" columns
grouped_data = df.groupby(['Artist', 'Projects', 'Point: Customer Name', 'Date'])

# Calculate the difference between the maximum and minimum "End Time" values for each group,
# as well as the sum of the "End Date" values
result = grouped_data.agg({'End Date': lambda x: x.max() - x.min(),
                           'End Date': ['sum']})

# Flatten the column index by renaming the columns
result.columns = ['Working Time', 'End Date Total']

# Reset the index to turn the grouped columns into regular columns
result = result.reset_index()

In [268]:
result.sum()

Дата окончания работы   711 days 05:04:00
dtype: timedelta64[ns]

In [271]:
result_data = result.groupby(['Проекты', 'Точка: Customer Name', 'Исполнитель', 'Дата']).agg({'Дата окончания работы': ['sum']})

In [279]:
result_data[:][:510]

                                                                 Дата окончания работы
                                                                                   sum
Проекты   Точка: Customer Name     Исполнитель        Дата
A-Product Magnum (НСФ №76)         ast028@contineo.kz 2023-02-01       0 days 03:14:00
                                                      2023-02-02       0 days 00:02:00
                                                      2023-02-04       0 days 00:01:00
                                                      2023-02-06       0 days 00:17:00
                                                      2023-02-09       0 days 02:41:00
...                                                                                ...
          Magnum Express (НСФ №60) ast024             2023-02-02       0 days 00:09:00
                                                      2023-02-04       0 days 00:10:00
                                                      2023-02-06       0 days 00:06:00
                                                      2023-02-09       0 days 00:09:00
                                                      2023-02-11       0 days 00:06:00

[510 rows x 1 columns]

In [280]:
result_data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8586 entries, ('A-Product', 'Magnum (НСФ №76)', 'ast028@contineo.kz', Timestamp('2023-02-01 00:00:00')) to ('Фото-селфи', 'Тоймарт Ужет', 'alm020', Timestamp('2023-02-03 00:00:00'))
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   (Дата окончания работы, sum)  8586 non-null   timedelta64[ns]
dtypes: timedelta64[ns](1)
memory usage: 113.7+ KB

In [ ]:
Как подсчитать сумму  timedelta64[ns]

In [283]:
result.to_excel('result.xlsx')

In [ ]:
import pandas as pd

# Create a sample dataframe with a timedelta64[ns] column
df = pd.DataFrame({
    'Start Time': pd.to_datetime(['2022-01-01 12:00:00', '2022-01-01 13:00:00']),
    'End Time': pd.to_datetime(['2022-01-01 13:00:00', '2022-01-01 15:00:00'])
})

# Calculate the duration of each row
df['Duration'] = df['End Time'] - df['Start Time']

# Calculate the sum of the Duration column
total_duration = df['Duration'].sum()

print(total_duration)

In [284]:
# Group data by "Project", "Point: Code", "Date" and "Исполнитель" columns
grouped_data = df.groupby(['Исполнитель','Проекты', 'Точка: Customer Name', 'Дата'])

# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'Дата окончания работы': lambda x: x.max() - x.min()})

# Rename the "End Time" column to "Working Time"
result = result.rename(columns={'Дата окончания работы': 'Working Time'})

# Group the result by "Artist" and calculate the total work time for each performer
total_work_time = result.groupby('Исполнитель')['Working Time'].sum()

print(total_work_time)

Исполнитель
akb001                4 days 15:19:00
akb002                3 days 04:25:00
akb003@contineo.kz    1 days 11:45:00
akb004                4 days 05:25:00
alm001               19 days 19:28:00
                           ...
trk001                6 days 03:58:00
trk002@contineo.kz    2 days 04:50:00
trz001                7 days 10:00:00
trz002                5 days 05:09:00
usk001                3 days 02:47:00
Name: Working Time, Length: 118, dtype: timedelta64[ns]

In [285]:
total_work_time.to_excel('total_work_time.xlsx')

In [ ]:
# Group data by "Artist", "Project", "Point: Code", "Date" columns
grouped_data = df.groupby(['Artist', 'Projects', 'Point: Customer Name', 'Date'])

# Calculate the difference between the maximum and minimum "End Time" values for each group
result = grouped_data.agg({'End Date': lambda x: x.max() - x.min()})

# Rename the "End Date" column to "Working Time"
result = result.rename(columns={'End Date': 'Working Time'})

# Group the result by "Artist" and calculate the total work time for each performer
total_work_time = result.groupby('Artist')['Working Time'].sum()

print(total_work_time)